spring:
  application:
    name: daily-embedded

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER:}
    password: ${SMTP_PASS:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8181

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

app:
  api:
    key: ${APP_API_KEY:changeme}
  llm:
    api-key: ${LLM_API_KEY:}
    provider-url: ${LLM_PROVIDER_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent}
    provider-type: ${LLM_PROVIDER_TYPE:gemini}
  delivery:
    default-hour: ${DEFAULT_DELIVERY_HOUR:6}

logging:
  level:
    com.acme.dailyembedded: INFO
    org.springframework.mail: WARN
    org.hibernate.SQL: WARN
